Replacing: slf4j with jul
algolia/algoliasearch-client-java pull request #565
Opened 2019-04-30 15:51 UTC by Ant-hem

Replaced SLF4J with Java.Util.logging for tracing requests/responses

Removing slf4j allow to remove on more dependency of the library and
to simplify the shading process.

 - Added: JUL in HttpTransport with Log.FINEST level
 - Removed: SLF4J and Logback from pom.xml
 - Updated: logging.properties

 To activate JUL please set in logging.properties
 .level=FINEST
 com.algolia.search.HttpTransport=FINEST
 java.util.logging.ConsoleHandler.level=FINEST

 and set:
 -Djava.util.logging.config.file="logging.properties-path"

2019-05-02 09:28 UTC, BenoitPerrot requested changes

2019-05-02 09:28 UTC, BenoitPerrot commented on algoliasearch-core/src/main/java/com/algolia/search/HttpTransport.java
> +  private static final Logger LOGGER = Logger.getLogger(HttpTransport.class.getName());
For another commit: ensure all static-final are uppercase:
- make javaVersion uppercase in Config.base
- if possible add a rule in the formatting configuration

2019-05-02 09:28 UTC, BenoitPerrot commented on algoliasearch-core/src/test/resources/logging.properties
> +org.apache.http.level=WARNING
-1: Add back the carriage return at the end of the line

2019-05-02 09:28 UTC, BenoitPerrot commented on pom.xml
>                                  <promoteTransitiveDependencies>true</promoteTransitiveDependencies>
-1: Remove this promoteTransitiveDependencies, as now unnecessary

This was introduced to have "algoliasearch-apache-uber" list "slf4j-api" as a dependency in its reduced pom.

2019-05-02 12:31 UTC, Ant-hem commented
All good @BenoitPerrot ! I will submit another PR with the formatting rules later :)

2019-05-02 12:53 UTC, BenoitPerrot commented on algoliasearch-core/src/test/resources/logging.properties
> +org.apache.http.level=WARNING
Hmm 🤔 This shouldn't be necessary

2019-05-02 13:03 UTC, Ant-hem commented on algoliasearch-core/src/test/resources/logging.properties
> +org.apache.http.level=WARNING
Good catch 😄

2019-05-06 08:16 UTC, BenoitPerrot approved these changes

2019-05-06 08:19 UTC, merged