Added: userData in IndexSettings
algolia/algoliasearch-client-java pull request #579
Opened 2019-06-11 10:53 UTC by Ant-hem

| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no     
| Related Issue     | Fix: #577
| Need Doc update   | no (already done)

2019-06-25 09:45 UTC, aseure approved these changes

2019-06-25 09:47 UTC, aseure requested changes
According to https://github.com/algolia/doc/pull/3228/files it seems like `userData` in the settings is just a `Map<String,Object>`. The `List<Map<String,Object>>` is only in the search response's `userData` field if I'm not mistaken.

2019-06-25 13:43 UTC, Ant-hem commented
> According to https://github.com/algolia/doc/pull/3228/files it seems like `userData` in the settings is just a `Map<String,Object>`. The `List<Map<String,Object>>` is only in the search response's `userData` field if I'm not mistaken.

My bad. Fixed it with 517f175.

2019-07-01 08:40 UTC, aseure approved these changes

2019-07-05 07:17 UTC, merged